name: Tests

on: [push, pull_request]

jobs:
  test:
    name: ${{ matrix.ruby }} on ${{ matrix.os }}${{ matrix.name_suffix }}
    strategy:
      matrix:
        os: [ubuntu-20.04]
        ruby: ['2.7']
        architecture: [default]
        name_suffix: ['']
        experimental: [false]
        exclude:
          - os: windows-2019
            ruby: jruby-1.7
        include:
          - os: ubuntu-20.04
            ruby: truffleruby-head
            achitecture: default
            name_suffix: ' (experimental)'
            experimental: true
      fail-fast: false
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    steps:
      - uses: actions/checkout@v2
      - if: startsWith(matrix.ruby, '1.') || startsWith(matrix.ruby, '2.0') || startsWith(matrix.ruby, 'jruby-1.7') || startsWith(matrix.ruby, 'jruby-9.0')
        uses: philr/setup-ruby@legacy-v1
        with:
          ruby-version: ${{ matrix.ruby }}
          architecture: ${{ matrix.architecture }}
          bundler-cache: true
      - if: ${{ !(startsWith(matrix.ruby, '1.') || startsWith(matrix.ruby, '2.0') || startsWith(matrix.ruby, 'jruby-1.7') || startsWith(matrix.ruby, 'jruby-9.0')) }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - run: ruby --version
      - run: gem --version
      - run: bundle --version
      - run: bundle exec rake test
        env:
          TESTOPTS: --verbose
